### ISSUE TITLE
Traversing XmlDiff

### ISSUE THREAD

**Issue by 0xAxPx** [andyglow/scala-xml-diff#9]
Hello
Thank you for such lib. I'm sure that guthub is not a right place to ask a question, and yet would you please advise if there is a way under a hood to traverse Neq resulting collection to futher sort it out if it has an element(attribute/child) to be ignored. To short, i would like to apply ignore logic for xml-diff.

Thank you for any help!

**Comment by andyglow** [comment]
Hello, Alex!
`Neq` case class contains essentially a patch, collection of differences rather then collection of original elements. If that information is sufficient for you to decide about filtering, go ahead and use it, otherwise you would need something more tricky.
Could you briefly describe what you need, may be with examples?

**Comment by 0xAxPx** [comment]
Hello, Andrey
I missed the fact that Neq includes a patch, I'm sorry. The goal is to process somehow a collection of diff fundings with an extra logic to exclude attributes etc.
